# Generated by Django 4.2.4 on 2023-09-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=250, verbose_name='порода')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='кличка')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='фото')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='ДР')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.breed')),
            ],
            options={
                'verbose_name': 'собака',
                'verbose_name_plural': 'собаки',
                'ordering': ('breed', 'name'),
            },
        ),
    ]
