# Generated by Django 4.2.4 on 2023-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'порода', 'verbose_name_plural': 'породы'},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ('name', 'breed'), 'verbose_name': 'собака', 'verbose_name_plural': 'собаки'},
        ),
        migrations.AddField(
            model_name='breed',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
    ]
