# Generated by Django 4.2.4 on 2023-09-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_alter_breed_options_alter_dog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics/', verbose_name='Картинка'),
        ),
    ]
