# Generated by Django 4.2.4 on 2023-09-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_alter_dog_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='кличка')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='ДР')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.breed', verbose_name='порода')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.dog', verbose_name='собака')),
            ],
        ),
    ]
